!PROGRAM TO CHECK THE VALIDITY OF RANDOM NUMBERS PRODUCED BY FORTRAN
!AUTHOR 	:: KAZ
!DATE 		:: 09.08.2019, FRIDAY
!CONTEXT	:: COMPUTATIONAL PHYSICS MOOC COURSE NPTEL - PRACTICE WEEK 2

PROGRAM RANDOMNESS_CHECK
	USE STATISTICAL_ROUTINES
	IMPLICIT NONE
	INTEGER							::	I,N,K  								! I - LOOP COUNTER,N - NUM OF RAND NUMS, K - NUM OF MOMENTS,VARIANCE AND AUTO-CORRELATIONS TO BE PROCESSED
	REAL 							::	MEAN,SD,MOMENT_ARRAY,ACK			! SIGMA - VARIANCE, ACK - K-TH AUTO CORRELATION
	REAL,DIMENSION(:),ALLOCATABLE	::	RANDARRAY							! ARRAY TO HOLD GENERATED RANDOM NUMS
	!REAL 							::  MOMENT,AUTO_CORRELATION				! FUNCTION RETURN TYPE DECLERATIONS

	OPEN(UNIT = 1, FILE = "RANDNUMS_SERIES.DAT")			! FILE TO STORE RANDOM NUMS AS A SERIES
	OPEN(UNIT = 2, FILE = "RANDNUMS_XY_SCATTERPLOT.DAT")	! FILE TO STORE RANDOM NUMS AS : RN(I) RN(I+1)
	OPEN(UNIT = 3, FILE = "RANDNUMS_MOMENTS.DAT")			! FILE TO STORE MOMENTS OF RANDOM NUMBER SERIES
	OPEN(UNIT = 4, FILE = "RANDNUMS_AUTO_CORRELATIONS.DAT")	! FILE TO STORE AUTO CORRELATIONS OF RANDOM NUMBER SERIES

	WRITE(*,*) "ENTER THE SIZE OF RANDOM NUMBER ARRAY TO BE PRODUCED:"
	READ(*,*) N

	WRITE(*,*) "ENTER NUMBER OF MOMENTS,VARIANCES AND AUTO CORRELATIONS TO BE PRINTED:"
	READ(*,*) K

	ALLOCATE(RANDARRAY(N))

	! GENERATES N RANDOM NUMBERS AND WRITES THEM TO THE FILE RANDNUMS_SERIES.DAT
	DO I = 1,N
		CALL RANDOM_NUMBER(RANDARRAY(I))
		WRITE(1,*) I,RANDARRAY(I)
	END DO

	! XY SCATTER PLOT DATA BETWEEN SUCCESSIVE RANDOM NUMBERS,WRITTEN TO THE FILE RANDNUMS_XY_SCATTERPLOT.DAT
	DO I = 1,N-1
		CALL RANDOM_NUMBER(RANDARRAY(I))
		WRITE(2,*) RANDARRAY(I),RANDARRAY(I+1)
	END DO

	CALL STATS(N,RANDARRAY,MEAN,SD)
	WRITE(*,*)  "	MEAN = ", MEAN
	WRITE(*,*)  "	SD   = ", SD

	DO I = 1,K
		MOMENT_ARRAY 	= MOMENT(N,RANDARRAY,I)
		ACK				= AUTO_CORRELATION(N,RANDARRAY,I-1)
		WRITE(3,*)	I,MOMENT_ARRAY	! WRITES MOMENTS TO THE FILE RANDNUMS_MOMENTS.DAT
		WRITE(4,*)	I,ACK			! WRITES AUTO CORRELATIONS TO THE FILE RANDNUMS_AUTO_CORRELATIONS.DAT
	END DO

	DEALLOCATE(RANDARRAY)
END PROGRAM RANDOMNESS_CHECK
 
