MODULE STATISTICAL_ROUTINES

	USE MOMENT_ROUTINE
	IMPLICIT NONE
CONTAINS	
	SUBROUTINE STATS(LEN,ARRAY,MEAN,SD)
		IMPLICIT NONE
		INTEGER 			:: 	LEN,I
		REAL,DIMENSION(LEN)	::	ARRAY
		REAL,INTENT(OUT)	:: 	MEAN,SD
		REAL 				::	MEANSQR,SUMOFSQR

		SUMOFSQR = 0.0D0

		MEANSQR = MOMENT(LEN,ARRAY,2)

		MEAN = SUM(ARRAY) / REAL(LEN)
		SD	= SQRT(MEANSQR - (MEAN * MEAN))
	END SUBROUTINE STATS


	FUNCTION VARIANCE(LEN,ARRAY,K) RESULT(RET_VARIANCE)
		IMPLICIT NONE
		INTEGER				::	LEN,K,I
		REAL,DIMENSION(LEN)	::	ARRAY
		REAL 				:: 	SUM_OF_PRODUCTS
		REAL 				::	RET_VARIANCE,MEAN_SQR 

		SUM_OF_PRODUCTS = 0.0D0

		MEAN_SQR = MOMENT(LEN,ARRAY,1)**2

		DO I = 1,LEN-K
			SUM_OF_PRODUCTS = SUM_OF_PRODUCTS + ARRAY(I)*ARRAY(I+K)
		END DO

		RET_VARIANCE = (SUM_OF_PRODUCTS / REAL(LEN-K)) - MEAN_SQR
	END FUNCTION VARIANCE

	FUNCTION AUTO_CORRELATION(lEN,ARRAY,K) RESULT(AC)
		INTEGER				::	LEN,K
		REAL,DIMENSION(LEN)	::	ARRAY
		REAL 				::	AC

		AC = VARIANCE(LEN,ARRAY,K)/VARIANCE(LEN,ARRAY,0)
	END FUNCTION AUTO_CORRELATION

END MODULE STATISTICAL_ROUTINES